name: "Swift Doc Deployment"
description: "Deploys the Swift documentation to GitHub pages."

branding:
  icon: "code"
  color: "blue"

inputs:
  target:
    description: "The Swift package target to generate documentation for."
    required: true
  branch:
    description: "The branch where the documentation will be deployed."
    required: false
    default: "gh-pages"
  name:
    description: "The name for Git commits."
    required: false
    default: "${{github.actor}}"
  email:
    description: "The email address for Git commits."
    required: false
    default: "${{github.actor}}@users.noreply.github.com"

runs:
  using: "composite"
  steps:
    - name: Build the Swift doc
      shell: bash
      run: |
        mkdir -p docs
        swift package --allow-writing-to-directory docs \
          generate-documentation --target "${{inputs.target}}" \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path "${{inputs.target}}" \
          --output-path docs

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "${{inputs.name}}"
        git config --global user.email "${{inputs.email}}"
        git config --global --add safe.directory /github/workspace

    - name: Prepare the deployment branch
      shell: bash
      run: |
        git checkout -B "${{inputs.branch}}"
        git push origin "${{inputs.branch}}" -f

    - name: Deploy to GitHub pages
      shell: bash
      run: |
        git add docs/ -f
        git commit -m "Deploy Swift Doc"
        git push origin $(git subtree split --prefix=docs/):${{inputs.branch}} -f
