name: "Swift Doc Deployment"
description: "Deploys the Swift documentation to GitHub pages."
author: "G1Joshi"

branding:
  icon: "code"
  color: "blue"

inputs:
  target:
    description: "The Swift package target to generate documentation for."
    required: true

outputs:
  page-url:
    description: "URL of the deployed GitHub Pages site"
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Add docc plugin
      shell: bash
      run: |
        swift package --disable-sandbox add-dependency https://github.com/apple/swift-docc-plugin --branch main
        swift package resolve

    - name: Create directory
      shell: bash
      run: mkdir -p docs

    - name: Build the Swift doc
      shell: bash
      run: swift package --allow-writing-to-directory docs generate-documentation --target "${{inputs.target}}" --disable-indexing --transform-for-static-hosting --hosting-base-path "${{inputs.target}}" --output-path docs

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: docs

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
